### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by qimiaohao** [theHamsta/farneback3d#7]
Hi theHamsta:
  I am interested in your optical flow 3d code. I really need it in my PhD project. However, I have some problem when import it. I install it in the anacoda. First, it always has some problem of installing the pycuda. Then, I used the method in the stackoverflow(https://stackoverflow.com/questions/64286145/cant-install-pycuda-with-pip), using the pipwin install pycuda(I am window operation system). Now I can isntall farneback3d successfully in the anaconda. However, when I import it, it has  some problems. Can you have a check when you have time. Thank you, it is very important to my PhD project, I will be very appreciated if you can help me. 

Traceback (most recent call last):
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\pytools\__init__.py", line 708, in wrapper
    return func._memoize_dic[args]  # noqa: E501 # pylint: disable=protected-access
AttributeError: 'function' object has no attribute '_memoize_dic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\pytools\prefork.py", line 47, in call_capture_output
    stderr=PIPE)
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/research/scattering_ad-holo/code/Miao_Code/Differential-Holographic-Volume-Imaging/version_after20211112/code/pytorch/test/test_of3d_far.py", line 1, in <module>
    import farneback3d
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\farneback3d\__init__.py", line 9, in <module>
    from farneback3d._farneback3d import Farneback, warp_by_flow
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\farneback3d\_farneback3d.py", line 16, in <module>
    import farneback3d._utils
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\farneback3d\_utils.py", line 44, in <module>
    _mod = SourceModule(_read_data)
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\pycuda\compiler.py", line 358, in __init__
    include_dirs,
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\pycuda\compiler.py", line 298, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\pycuda\compiler.py", line 93, in compile_plain
    checksum.update(get_nvcc_version(nvcc).encode("utf-8"))
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\pytools\__init__.py", line 711, in wrapper
    result = func(*args)
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\pycuda\compiler.py", line 16, in get_nvcc_version
    result, stdout, stderr = call_capture_output(cmdline)
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\pytools\prefork.py", line 221, in call_capture_output
    return forker.call_capture_output(cmdline, cwd, error_on_nonzero)
  File "C:\Users\qim\AppData\Local\Continuum\anaconda3\envs\holo-encoding\lib\site-packages\pytools\prefork.py", line 58, in call_capture_output
    raise ExecError("error invoking '{}': {}".format(" ".join(cmdline), e))
pytools.prefork.ExecError: error invoking 'nvcc --version': [WinError 2] The system cannot find the file specified

**Comment by theHamsta** [comment]
The installer can't find nvcc. Please contact pycuda for support on how to install their project
